

<div id="rightMenu" style="position:absolute; top:10px; right:10px;">
   
        <input type="checkbox" id="checkLayerWeatherAll" onClick="showAll()"/>All
        </br></br>
        <input type="checkbox" id="checkLayerWeatherWind" class="weather" onClick="showWind()" />Wind
        </br></br>
        <input type="checkbox" id="checkLayerWeatherWaves" class="weather" onClick="showWaves()"/>Waves
    </br></br>
    <input type="checkbox" id="checkLayerWeatherSwell" class="weather" onClick="showSwell()"/>Swell
</br></br>
<input type="checkbox" id="checkLayerWeatherCurrent" class="weather" onClick="showCurrent()"/>Current
</br></br>
<input type="checkbox" id="checkNone" onClick="clearAll()"/>None     
</div>